- hosts: adhoc-vm
  tasks:
  - name: download key
    become: true
    become_user: root
    shell: |
      sudo apt-get update
      sudo apt-get install -y python-pip
      sudo apt-get install -y python3-pip
      pip install --upgrade pip
      pip3 install --upgrade pip
